// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkyeviihektcypagozbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpreWV2aWloZWt0Y3lwYWdvemJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzQxMzgsImV4cCI6MjA2MDM1MDEzOH0.6qlV4j7441PHYvZ-Xxy4QehMhi6OF_blhLtyM7rdWEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);